export async function POST(request: Request) {
  try {
    const { studentId, studentName, data } = await request.json()

    // Generate CSV content
    const csvContent = generateCSV(studentName, data)

    // Generate PDF-like HTML for printing
    const htmlContent = generateHTML(studentName, data)

    return Response.json({
      success: true,
      csv: csvContent,
      html: htmlContent,
      timestamp: new Date().toISOString(),
    })
  } catch (error) {
    console.error("Export error:", error)
    return Response.json({ error: "Failed to generate report" }, { status: 500 })
  }
}

function generateCSV(studentName: string, data: any): string {
  const headers = ["Metric", "Value"]
  const rows = [
    ["Student Name", studentName],
    ["Level", data.level],
    ["Lessons Completed", data.lessonsCompleted],
    ["Audio Hours", data.audioHours],
    ["Overall Progress", `${data.overallProgress}%`],
    [""],
    ["Weekly Performance"],
    ...(data.weeklyPerformance?.map((w: any) => [w.week, w.score]) || []),
    [""],
    ["Skills Assessment"],
    ...(data.skills?.map((s: any) => [s.skill, `${s.score}%`]) || []),
  ]

  return [headers.join(","), ...rows.map((row) => row.map((cell) => `"${cell}"`).join(","))].join("\n")
}

function generateHTML(studentName: string, data: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${studentName} - ILLO Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1f2937; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
    .section { margin-top: 30px; }
    .metrics { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-top: 15px; }
    .metric-box { border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px; }
    .metric-label { color: #6b7280; font-size: 12px; text-transform: uppercase; }
    .metric-value { font-size: 24px; font-weight: bold; color: #1f2937; margin-top: 5px; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { background-color: #f3f4f6; font-weight: 600; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
  </style>
</head>
<body>
  <h1>Learning Progress Report - ILLO Dashboard</h1>
  <p><strong>Student:</strong> ${studentName}</p>
  <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>

  <div class="section">
    <h2>Performance Summary</h2>
    <div class="metrics">
      <div class="metric-box">
        <div class="metric-label">Level</div>
        <div class="metric-value">${data.level}</div>
      </div>
      <div class="metric-box">
        <div class="metric-label">Lessons Completed</div>
        <div class="metric-value">${data.lessonsCompleted}</div>
      </div>
      <div class="metric-box">
        <div class="metric-label">Audio Hours</div>
        <div class="metric-value">${data.audioHours}h</div>
      </div>
      <div class="metric-box">
        <div class="metric-label">Overall Progress</div>
        <div class="metric-value">${data.overallProgress}%</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Skills Assessment</h2>
    <table>
      <thead>
        <tr>
          <th>Skill</th>
          <th>Score</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        ${
          data.skills
            ?.map(
              (s: any) => `
          <tr>
            <td>${s.skill}</td>
            <td>${s.score}%</td>
            <td>${s.score >= 80 ? "Proficient" : s.score >= 60 ? "Developing" : "Needs Support"}</td>
          </tr>
        `,
            )
            .join("") || ""
        }
      </tbody>
    </table>
  </div>

  <div class="footer">
    <p>This report was generated by ILLO (Interactive Language Learning Observer)</p>
    <p>For questions or concerns, please contact your instructor.</p>
  </div>
</body>
</html>
  `
}
